### ISSUE TITLE
Deployment hooks

### ISSUE THREAD

**Issue by sosedoff** [sosedoff/shuttle#6]
There is a limited support for deployment hooks at the moment. Overall list of hooks should 
include the following:
- `before_setup`
- `after_setup`
- `before_checkout_code`
- `after_checkout_code`
- `before_link_release`
- `after_link_release`
- `before_rollback`
- `after_rollback`

Any hook command (except `after_link_release`) that returns non-zero exit status will trigger
deploy termination and the whole release will be deleted. Hook `link_release` is the last step where deploy could be cancelled.

General deployment steps are:
- `setup` - Create directories necessary for application (releases, shared, tmp, etc)
- `update_code` - Clone or update repository code
- `checkout_code` - Checkout master branch (or any other) into new release directory
- `link_release` - Link new release to `current` directory

Each individual deployment strategy could expose a set of additional hooks. For instance,
for `rails` strategy it could be `after_assets_precompile` hook that'll provide extra flexibility. 

Example hooks config:

``` yml
hooks:
  before_link_release:
    - "cd $RELEASE_PATH && rake assets:build"
    - "cd $RELEASE_PATH && rake assets:upload"
  after_link_release:
    - "cd $RELEASE_PATH && ruby ./notify_deployment_success"
```
